#!/bin/sh
alias ls='ls --color=auto'
alias ll='ls -la --color=auto'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# custom aliases
alias srczsh="source $ZDOTDIR/.zshrc"
alias zshconfig="nvim $ZDOTDIR/.zshrc"
alias act='source ./.venv/bin/activate'
alias inv='nvim $(fzf --preview="bat --color=always {}")'
alias ...='cd ../..'

# TMUX aliases
alias tt="python3 $HOME/projects/tmux-sess/main.py"
alias ta='tmux a'
alias tl='tmux ls'

# Suffix aliases
alias -s md=$EDITOR
alias -s py=$EDITOR
alias -s go=$EDITOR
alias -s json="jless"
alias -s yaml="bat -l yaml"

# Global aliases
alias -g C="| wl-copy"
alias -g L="| less"
alias -g JQ="| jq"
alias -g NE="2>/dev/null"
alias -g ND=">/dev/null"
alias -g NUL=">/dev/null 2>1"


# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"
