#!/bin/sh
HISTFILE="${XDG_DATA_HOME:-${HOME}/.local/share}"/zsh/history
HISTSIZE=5000
SAVEHIST=5000
HISTDUP=erase

export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.miniconda/bin:$PATH
export PATH="$PATH:$(go env GOPATH)/bin" 
export EDITOR=nvim
export FZF_DEFAULT_OPTS="--style minimal --color 16 --layout=reverse --height 30% --preview='bat -p --color=always {}'"
export FZF_CTRL_R_OPTS="--style minimal --color 16 --info inline --no-preview"

autoload edit-command-line
zle -N edit-command-line
# Optional: Bind Ctrl-x Ctrl-e (Emacs style)
bindkey '^X^E' edit-command-line

# chpwd hook for python
chpwd() {
  if [[ -d .venv ]]; then
    source .venv/bin/activate
  elif [[ -d venv ]]; then
    source .venv/bin/activate
  elif [[ -n "$VIRTUAL_ENV" ]]; then
    deactivate
  fi
}
