#!/bin/sh
HISTFILE="${XDG_DATA_HOME:-${HOME}/.local/share}"/zsh/history
HISTSIZE=5000
SAVEHIST=5000
HISTDUP=erase

export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.miniconda/bin:$PATH
export EDITOR=nvim
